version: '3'

services:

 nginx:
  image: nginx
  ports:
  - 8090:80
  volumes:
  - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  - ./nginx/logs/:/var/log/nginx

 dc-keycloak:
  image: quay.io/keycloak/keycloak:22.0.5
  environment:
    KEYCLOAK_LOG_LEVEL: DEBUG
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: myadminpwd
    KC_PROXY: edge
    KC_PROXY_MODE: edge
    KC_HTTP_ENABLED: true
    KC_HOSTNAME_STRICT: false
    KC_HOSTNAME_PATH: /auth
    KC_HOSTNAME_URL: http://localhost:8090/auth
    KC_HOSTNAME_ADMIN_URL: http://localhost:8090/auth
  command:
    - start-dev
  volumes:
    - ./volumes/keyckloak:/opt/keycloak/data/h2
  ports:
    - 100:8080


 angular-app:
    build:
      context: ../Front
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

 dotnet-api:
    build:
      context: ../API/ProductApi
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "server=bdd_mysql;port=3306;database=gestion_produit;user=root;password=admin"
    ports:
      - "8080:8080"
 db:
    build:
      context: ../database
      dockerfile: Dockerfile
    container_name: bdd_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      #MYSQL_DATABASE: gestion_produit
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
     # - ../database/:/docker-entrypoint-initdb.d/


volumes:
  db_data:
