version: '3'

services:
 nginx:
  image: nginx
  ports:
  - 8090:80
  volumes:
  - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  - ./nginx/logs/:/var/log/nginx

 angular-app:
    build:
      context: ../Front
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production

 dotnet-api:
    build:
      context: ../API/ProductApi
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "server=bdd_mysql;port=3306;database=gestion_produit;user=root;password=admin"
    ports:
      - "8080:8080"
 db:
    build:
      context: ../database
      dockerfile: Dockerfile
    container_name: bdd_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      #MYSQL_DATABASE: gestion_produit
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
     # - ../database/:/docker-entrypoint-initdb.d/


volumes:
  db_data:
