version: '3'
services:
 angular-app:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - NODE_ENV=production

 dotnet-api:
    build:
      context: ./API/ProductApi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
 db:
    build: .
    container_name: bdd_mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: gestion_produit
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
